name: Build APK
on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: |
          cd artifacts/noor-app
          flutter pub get
      - name: Build APK
        run: |
          cd artifacts/noor-app
          flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: artifacts/noor-app/build/app/outputs/flutter-apk/app-debug.apk
